#
# Main configuration file
# KeepInventory version: 2.0.0
#

# CHANGE IF NECESSARY
# If you changed this field and someone already had inventory retention enabled, they will need to enable it again.
key_name: "keepInventory"

# Default keep_inventory state
default_keep_inventory_state: false

# Aliases for the keepinventory command
command_aliases:
  - "keepinv"
