#
# Main KeepInventory configuration file
# Plugin version: 2.0.0
#

# CHANGE IF NECESSARY
# If you changed this field and someone already had inventory retention enabled, they will need to enable it again.
key_name: "keepInventory"

# Default inventory retention state
default_keep_inventory_state: false
